#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("LunchPac.Droid.Resource", IsApplication=true)]

namespace LunchPac.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::LunchPac.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::LunchPac.Droid.Resource.String.Hello;
			global::Splat.Resource.String.library_name = global::LunchPac.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int WWDarkBlue = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int WWLightBlue = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int WWLightMedBlue = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int WWMedDarkBlue = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int accent = 2130968579;
			
			// aapt resource value: 0x7f04000f
			public const int canceled = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int completed = 2130968590;
			
			// aapt resource value: 0x7f040008
			public const int darkgraycolor = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int in_progress = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int lightgray = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int not_started = 2130968589;
			
			// aapt resource value: 0x7f040001
			public const int primary = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int primary_dark = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int txt_field_bg = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int unscheduled = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int white = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int logowhite = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ww_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int newcross = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int previous = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030002
			public const int ApplicationName = 2130903042;
			
			// aapt resource value: 0x7f030001
			public const int Hello = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int library_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050004
			public const int App_EditTextStyle = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int MyTheme = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int MyTheme_ActionBar_TitleTextStyle = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int MyTheme_ActionBarStyle = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int MyTheme_Base = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int TabTextStyle = 2131034117;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
